server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/hrm_course
     username: root
     password: 123456
mybatis-plus:
  mapper-locations: classpath:com/lpc/hrm/mapper/*Mapper.xml
  type-aliases-package: com.lpc.hrm.domain,com.lpc.hrm.query
